# Generated by Django 6.0.7 on 2026-07-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('DRAFT', 'Draft'), ('REVEAL', 'Reveal'), ('CLUSTER', 'Cluster'), ('VOTE', 'Vote'), ('DISCUSS', 'Discuss'), ('COMPLETE', 'Complete')], default='DRAFT', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0, help_text='Increases by one on every transaction that mutates the board.')),
                ('votes_per_member', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='cycles.feedbackcycle')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
