# Generated by Django 6.0.7 on 2026-07-22 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISCUSSED', 'Discussed'), ('SKIPPED', 'Skipped'), ('DEFERRED', 'Deferred')], default='PENDING', max_length=20)),
                ('retrospective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='retro.retrospective')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='retro_cluster_name_not_blank')],
            },
        ),
    ]
