# Generated by Django 6.0.7 on 2026-07-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0002_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospective',
            name='clustering_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
