# Generated by Django 6.0.7 on 2026-07-23 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0003_retrospective_clustering_error'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='retro.cluster')),
                ('retrospective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='retro.retrospective')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['retrospective', 'user'], name='retro_vote_retro_user')],
                'constraints': [models.UniqueConstraint(fields=('retrospective', 'cluster', 'user'), name='retro_vote_unique_member_cluster'), models.CheckConstraint(condition=models.Q(('weight__gte', 1), ('weight__lte', 3)), name='retro_vote_weight_within_budget')],
            },
        ),
    ]
