# Generated by Django 6.0.7 on 2026-07-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0006_actionitem_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='retrospective',
            name='extraction_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
