# Generated by Django 6.0.7 on 2026-07-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0007_actionitem_excerpt_decision_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospective',
            name='extraction_summary_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
