# Generated by Django 6.0.7 on 2026-07-22 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('AUDIO', 'Audio recording'), ('VIDEO', 'Video recording'), ('TRANSCRIPT_FILE', 'Transcript file'), ('PASTED_TEXT', 'Pasted transcript')], max_length=20)),
                ('temp_path', models.CharField(blank=True, help_text='Where the media sits in the shared scratch volume, until it is deleted.', max_length=500, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('TRANSCRIBING', 'Transcribing'), ('EXTRACTING', 'Extracting'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('retrospective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_records', to='retro.retrospective')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'FAILED'), _negated=True), fields=('retrospective',), name='one_live_meeting_record_per_retrospective')],
            },
        ),
    ]
