# Generated by Django 6.0.7 on 2026-07-22 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text="Any day of the week you mean; it is stored as that week's Monday.")),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField(help_text='The deadline the team is told about. Nothing closes the cycle but a person.')),
                ('status', models.CharField(choices=[('COLLECTING', 'Collecting'), ('CLOSED', 'Closed')], default='COLLECTING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilitated_cycles', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='projects.project')),
            ],
            options={
                'ordering': ['-week_start', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'COLLECTING')), fields=('project',), name='cycles_feedbackcycle_one_collecting_per_project'), models.UniqueConstraint(fields=('project', 'week_start'), name='cycles_feedbackcycle_unique_project_week')],
            },
        ),
    ]
