# Generated by Django 6.0.7 on 2026-07-22 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('START', 'Start'), ('STOP', 'Stop'), ('CONTINUE', 'Continue')], max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cycles.feedbackcycle')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['cycle', 'author'], name='cycles_card_cycle_author')],
                'constraints': [models.CheckConstraint(condition=models.Q(('text__regex', '^\\s*$'), _negated=True), name='cycles_card_text_not_blank')],
            },
        ),
    ]
