# Generated by Django 6.0.7 on 2026-07-22 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_count', models.PositiveIntegerField(default=0, help_text='How many cards this member wrote, attributed and anonymous together.')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='The day this member first submitted, or NULL if they submitted nothing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='cycles.feedbackcycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_participation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cycle_id', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'user'), name='cycles_cycleparticipation_unique_cycle_user'), models.CheckConstraint(condition=models.Q(models.Q(('card_count', 0), ('submitted_at__isnull', True)), models.Q(('card_count__gt', 0), ('submitted_at__isnull', False)), _connector='OR'), name='cycles_cycleparticipation_count_matches_submitted')],
            },
        ),
    ]
