# Generated by Django 6.0.7 on 2026-07-22 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_card_public_id'),
        ('retro', '0002_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='retro.cluster'),
        ),
    ]
