apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres-course-assistant
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    database: course_assistant
    user: user
    isDefault: true
    editable: true
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
